### ISSUE TITLE
Did you try use apex for learner ?

### ISSUE THREAD

**Issue by Begin19** [lucidrains/byol-pytorch#29]
Hi lucidrains! Thanks for your amazing packages!

Could you please give me some advice?

I'm trying to use apex with byol-pytorch (with default augmentation - kornia) in DDP mode and got such error:

> Traceback (most recent call last):
  File "byol.py", line 221, in <module>
    main(args)
  File "byol.py", line 160, in main
    loss = learner(X)
  File "/root/PycharmProjects/torch16projects/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/PycharmProjects/torch16projects/venv/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/root/PycharmProjects/torch16projects/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/PycharmProjects/torch16projects/venv/lib/python3.6/site-packages/apex/amp/_initialize.py", line 197, in new_fwd
    **applier(kwargs, input_caster))
  File "/root/PycharmProjects/torch16projects/venv/lib/python3.6/site-packages/byol_pytorch/byol_pytorch.py", line 187, in forward
    image_one, image_two = self.augment(x), self.augment(x)
  File "/root/PycharmProjects/torch16projects/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/PycharmProjects/torch16projects/venv/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/root/PycharmProjects/torch16projects/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/PycharmProjects/torch16projects/venv/lib/python3.6/site-packages/kornia/augmentation/augmentation.py", line 63, in forward
    output = self.apply_transform(input, self._params)
  File "/root/PycharmProjects/torch16projects/venv/lib/python3.6/site-packages/kornia/augmentation/augmentation.py", line 709, in apply_transform
    return F.apply_crop(input, params)
  File "/root/PycharmProjects/torch16projects/venv/lib/python3.6/site-packages/kornia/augmentation/functional.py", line 595, in apply_crop
    input, params['src'], params['dst'], resample_mode, align_corners=align_corners)
  File "/root/PycharmProjects/torch16projects/venv/lib/python3.6/site-packages/kornia/geometry/transform/crop.py", line 177, in crop_by_boxes
    dst_trans_src: torch.Tensor = get_perspective_transform(src_box.to(tensor.dtype), dst_box.to(tensor.dtype))
  File "/root/PycharmProjects/torch16projects/venv/lib/python3.6/site-packages/kornia/geometry/transform/imgwarp.py", line 249, in get_perspective_transform
    X, LU = torch.solve(b, A)
RuntimeError: "solve_cpu" not implemented for 'Half'

Kornia is not support fp16 ? Or I'm doing something wrong? fp32 training is much expensive.
How can I fix it or maybe I can use some arbitrary aug function? 

Thanks for your time.

**Comment by lucidrains** [comment]
@Begin19 yea, unfortunately I ran into this problem with Kornia as well :( you should submit a ticket with them!

**Comment by lucidrains** [comment]
@Begin19 I hear mixed precision isn't even that great anymore in the new RTX 3090 series, so maybe not worth the effort

**Comment by Begin19** [comment]
Got it. Thanks

**Comment by luyvlei** [comment]
I use the amp builtin pytorch and it works well. 
```
    if args.amp:
        scaler = GradScaler()

    for e in range(args.epoch):
        for idx, images in enumerate(dataloader):
            optim.zero_grad()
            with autocast():
                loss = learner(images.to(device))
            
            if args.amp:
                scaler.scale(loss).backward()
                scaler.step(optim)
                scaler.update()
            else:
                loss.backward()
                optim.step()
            learner.update_moving_average() # update moving average of target encoder

            print("epoch:{}/{} iter:{}/{} loss={:.4f}".format(e, args.epoch, idx, len(dataset)//args.bs+1, loss.item()))
        # save your improved network
        scheduler.step()
        torch.save(resnet.state_dict(), args.save_path+'/byol_net_{}.pth'.format(e))
```
