### ISSUE TITLE
TPU/colab

### ISSUE THREAD

**Issue by whyrv** [lucidrains/byol-pytorch#33]
thanks for a very clean implementation. Have you enabled the PL TPU and tried it?
I tried it on your train.py following the [simple steps](https://pytorch-lightning.readthedocs.io/en/latest/tpu.html) for enabling TPU (8 cores) and I got the dreaded "Input tensor is not an XLA tensor: torch.FloatTensor lightning" error. It might help it go faster if you could fix+enable this.

**Comment by lucidrains** [comment]
@whyrv thanks! could you possibly provide the trace?

**Comment by whyrv** [comment]
sorry for the late response. I debugged it quite further. after fixing trivial issues of moving the tensors to xla, the fundamental issue is that the kornia augmentations that you use are not xla/tpu compatible.

**Comment by umbertov** [comment]
Hi, i've been getting the same problem using both kaggle and colab TPUs.
@lucidrains the stack trace is huge, so i put it here https://pastebin.com/DNeVpzTv 
The weird thing is it says `using: 0 TPU cores`. I've tried it on Kaggle too, and it gives the same exact error as the original poster, though. I can't post it right now but will asap

@whyrv you said you debugged it, would you mind sharing what you did? Perhaps you avoided using those kornia augmentations, how did you replace them?

**Comment by umbertov** [comment]
Hi @lucidrains I managed to get a stack trace of the error in the OP. I now know for sure that this happens for something wrong in the BYOL module, because i ran the exact same code with a supervised module and managed to get it training (and this is a whole other story, because of [this](https://github.com/PyTorchLightning/pytorch-lightning/issues/4829) problem)

```python
Traceback (most recent call last):
  File "train.py", line 271, in <module>
    best_lr = find_best_lr(model, trainer, num_training=30, train_dataloader = train_loader)
  File "train.py", line 217, in find_best_lr
    train_dataloader = train_dataloader)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/tuner/tuning.py", line 130, in lr_find
    datamodule,
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/tuner/lr_finder.py", line 172, in lr_find
    datamodule=datamodule)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 445, in fit
    results = self.accelerator_backend.train()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/tpu_accelerator.py", line 109, in train
    start_method=self.start_method
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 387, in spawn
    _start_fn(0, pf_cfg, fn, args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/tpu_accelerator.py", line 137, in tpu_train_in_process
    results = self.train_or_test()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/accelerator.py", line 66, in train_or_test
    results = self.trainer.train()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 494, in train
    self.train_loop.run_training_epoch()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 561, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 700, in run_training_batch
    self.training_step_and_backward(split_batch, batch_idx, opt_idx, optimizer, self.trainer.hiddens)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 813, in training_step_and_backward
    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 320, in training_step
    training_step_output = self.trainer.accelerator_backend.training_step(args)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/tpu_accelerator.py", line 149, in training_step
    output = self.trainer.model.training_step(*args)
  File "train.py", line 86, in training_step
    loss = self.forward(images)
  File "train.py", line 83, in forward
    return self.learner(images)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/byol_pytorch/byol_pytorch.py", line 214, in forward
    image_one, image_two = self.augment1(x), self.augment2(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/byol_pytorch/byol_pytorch.py", line 58, in forward
    return self.fn(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kornia/augmentation/base.py", line 204, in forward
    return self.apply_func(in_tensor, in_transform, self._params, return_transform)
  File "/usr/local/lib/python3.6/dist-packages/kornia/augmentation/base.py", line 167, in apply_func
    output = self.apply_transform(in_tensor, params)
  File "/usr/local/lib/python3.6/dist-packages/kornia/augmentation/augmentation.py", line 193, in apply_transform
    return F.apply_color_jitter(input, params)
  File "/usr/local/lib/python3.6/dist-packages/kornia/augmentation/functional/functional.py", line 360, in apply_color_jitter
    jittered = t(jittered)
  File "/usr/local/lib/python3.6/dist-packages/kornia/augmentation/functional/functional.py", line 354, in <lambda>
    lambda img: apply_adjust_hue(img, params)
  File "/usr/local/lib/python3.6/dist-packages/kornia/augmentation/functional/functional.py", line 780, in apply_adjust_hue
    transformed = adjust_hue(input, params['hue_factor'].to(input.dtype) * 2 * pi)
  File "/usr/local/lib/python3.6/dist-packages/kornia/enhance/adjust.py", line 134, in adjust_hue
    x_adjusted: torch.Tensor = adjust_hue_raw(x_hsv, hue_factor)
  File "/usr/local/lib/python3.6/dist-packages/kornia/enhance/adjust.py", line 105, in adjust_hue_raw
    if ((hue_factor < -pi) | (hue_factor > pi)).any():
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 27, in wrapped
    return f(*args, **kwargs)
RuntimeError: torch_xla/csrc/aten_xla_bridge.cpp:69 : Check failed: xtensor 
*** Begin stack trace ***
	tensorflow::CurrentStackTrace()
	torch_xla::bridge::GetXlaTensor(at::Tensor const&)
	torch_xla::AtenXlaType::lt(at::Tensor const&, at::Tensor const&)
	c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<at::Tensor (*)(at::Tensor const&, at::Tensor const&), at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&> >, at::Tensor (at::Tensor const&, at::Tensor const&)>::call(c10::OperatorKernel*, at::Tensor const&, at::Tensor const&)
	at::Tensor c10::Dispatcher::callWithDispatchKey<at::Tensor, at::Tensor const&, at::Tensor const&>(c10::TypedOperatorHandle<at::Tensor (at::Tensor const&, at::Tensor const&)> const&, c10::DispatchKey, at::Tensor const&, at::Tensor const&) const
	at::lt(at::Tensor const&, at::Tensor const&)
	
	
	at::Tensor c10::Dispatcher::callWithDispatchKey<at::Tensor, at::Tensor const&, at::Tensor const&>(c10::TypedOperatorHandle<at::Tensor (at::Tensor const&, at::Tensor const&)> const&, c10::DispatchKey, at::Tensor const&, at::Tensor const&) const
	at::Tensor::lt(at::Tensor const&) const
	
	_PyCFunction_FastCallDict
	_PyObject_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	
	_PyObject_FastCallDict
	
	PyObject_RichCompare
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	
	
	_PyObject_FastCallKeywords
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	
	
	_PyObject_FastCallKeywords
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	
	
	_PyObject_FastCallKeywords
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	
	
	_PyObject_FastCallKeywords
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
*** End stack trace ***
Input tensor is not an XLA tensor: torch.FloatTensor
```

**Comment by umbertov** [comment]
Hey, i can confirm that the culprit is the Kornia augmentations. I used `torchvision`'s ones and got rid of the problem.

For anyone in my situation reading this in the future, just define a function like

```python
from torchvision import transforms

def get_byol_transforms(image_size):
    return torch.nn.Sequential(*[

        transforms.RandomApply(
            torch.nn.ModuleList(
                [ transforms.ColorJitter(0.8, 0.8, 0.8, 0.2) ]
            )
        , p = 0.3),
        transforms.RandomGrayscale(p=0.2),
        transforms.RandomHorizontalFlip(),
        transforms.RandomApply(
            torch.nn.ModuleList(
                [ transforms.GaussianBlur((3, 3), (1.0, 2.0)) ]
            )
        , p = 0.2),
        transforms.RandomResizedCrop((image_size, image_size)),
        transforms.Normalize(
            mean=torch.tensor([0.485, 0.456, 0.406]),
            std=torch.tensor([0.229, 0.224, 0.225])),
    ])

```

and pass it to the BYOL constructor like `BYOL(..., augment_fn=get_byol_transforms(image_size))`.

@lucidrains if you'd like to test this as well and incorporate the change into the code (i.e. re-defining `DEFAULT_AUG` in the BYOL class and dropping the kornia dependency), this issue might as well be closed and marked as solved. I could create a PR for this but i'm too sleepy right now, maybe in the next few days
