### ISSUE TITLE
Error when running the model with DDP

### ISSUE THREAD

**Issue by SuhongMoon** [lucidrains/byol-pytorch#36]
Hi,

Thanks for proving such a cool implementation! When I ran your code with multiple GPUs, I ran into the below error.

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Traceback (most recent call last):
  File "train.py", line 139, in <module>
    trainer.fit(model, train_loader)
  File "/home/suhong/miniconda3/envs/byol/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 440, in fit
    results = self.accelerator_backend.train()
  File "/home/suhong/miniconda3/envs/byol/lib/python3.6/site-packages/pytorch_lightning/accelerators/ddp_spawn_accelerator.py", line 64, in train
    mp.spawn(self.ddp_train, nprocs=self.nprocs, args=(self.mp_queue, model,))
  File "/home/suhong/miniconda3/envs/byol/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/suhong/miniconda3/envs/byol/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 148, in start_processes
    process.start()
  File "/home/suhong/miniconda3/envs/byol/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/suhong/miniconda3/envs/byol/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/suhong/miniconda3/envs/byol/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/suhong/miniconda3/envs/byol/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/suhong/miniconda3/envs/byol/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/suhong/miniconda3/envs/byol/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/home/suhong/miniconda3/envs/byol/lib/python3.6/enum.py", line 46, in _break_on_call_reduce
    raise TypeError('%r cannot be pickled' % self)
TypeError: <Resample.BILINEAR: 1> cannot be pickled

Since there is no specification of accelerator type, pytorch-lightning assign ddp-spawn by default. Do you have any insight to resolve this error?

**Comment by SuhongMoon** [comment]
I figured out. I removed transforms.Lambda(expand_greyscale) by mistake.
