### ISSUE TITLE
Cannot get embedding

### ISSUE THREAD

**Issue by Yurushia1998** [lucidrains/byol-pytorch#56]
When I test on env with python 3.6 and torch 1.6, there is an error when I try to get embedding:
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    projection, embedding = learner(imgs, return_embedding = True)
  File "/home/dung/miniconda3/envs/tf_gpu_torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'return_embedding'

And it is weird that when I test on other env it works normally. Is there anyone know the reason and how to fix this?

**Comment by shivam-aggarwal** [comment]
what byol-pytorch version are you using?
Try using byol-pytorch==0.5.4 and torch==1.7.1
