### ISSUE TITLE
Expected to have finished reduction in the prior iteration before starting a new one. 

### ISSUE THREAD

**Issue by DingHuilsp** [lucidrains/byol-pytorch#92]
Traceback (most recent call last):
  File "/home/ma-user/work/byol-accelerate/train.py", line 27, in <module>
    trainer()
  File "/home/ma-user/anaconda3/envs/PyTorch-1.11/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ma-user/work/byol-accelerate/byol_pytorch/trainer.py", line 112, in forward
    loss = self.byol(images)
  File "/home/ma-user/anaconda3/envs/PyTorch-1.11/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ma-user/anaconda3/envs/PyTorch-1.11/lib/python3.9/site-packages/torch_npu/utils/module.py", line 188, in ddp_forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 159 160
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error

**Comment by lucidrains** [comment]
@DingHuilsp should be fixed
